### ISSUE TITLE
Feature Request - create migration files

### ISSUE THREAD

**Issue by smnirven** [yogthos/migratus-lein#2]
Would be great to have an additional method that creates the migration files for you, something like "lein migratus new create-users-table", which would create a file THETIMESTAMP_create-users-table.sql and drop it in your migrations directory for you.

**Comment by pupeno** [comment]
I been trying to implement this but I'm finding the abstraction of migrations a bit complex to deal with. Right now I'm stuck at this with issue #5.

**Comment by yogthos** [comment]
fixed by https://github.com/yogthos/migratus-lein/commit/c4bbcd7b2ba6ccc67ddb44e4534ce1245db27f5f
